### ISSUE TITLE
[ Question ] SPA

### ISSUE THREAD

**Issue by mintyPT** [goradd/goradd#39]
A couple of years ago with QCube for a bunch of projects. Since then, I never found anything that had a speed closer to it in terms of development. I think you were a big contributor to QCube and I recently discovered this repo and that QCubed is mostly dying.

These days, I'm mostly a full-stack dev. I work with backends build on nodejs with frontends done in react.

My question here is: When you started this project, did you thought about doing it with an API and a frontend? I mean, all the code generation would still be here for the front and back, but the backend and frontend would be split in two and you would have a modern SPA with a API on the back.

This would allow you to generate only the front or backend if necessary, plug other stuff to the api (example: mobile apps), have a frontend easy work it and with the possibility to had a huge amount of pre-existing modules from npm (for this I speak mostly for react and vue), and more that I won't list here because it's not important for the discussion.

**Comment by spekary** [comment]
Great question. Yes. Here is a big answer for why I am proceeding how I am.

One goal of the project is accessibility. Since this is a framework, I would prefer not to limit it to only modern browsers. I just checked in some fixes so basic forms will work with javascript turned off. Later on, I hope to make it Opera Mini compatible. So the html generation in the default widgets is going to support progressive enhancement. 

That said, neither do I want to limit to only HTML widgets. There are a ton of approaches to displaying javascript widgets. A few years ago I spoke with Mike Ho about this, and he thought the QCodo/QCubed approach could be adapted to AngularJS. I have thought about a React approach as well, and I have a private PHP version of a widget that does data synchronization for a MySQL database, sort of like CouchDB. Porting it to Goradd would not be hard and would provide the kind of data synchronization needed for a reactive approach, though pushing data down to the server is tricky in these situations.

I think another approach could be supporting WebComponents/Polymer. This is a little easier, because the widget can be declared through the HTML, and the widget can be designed to send its data to the server through the current Ajax mechanism very easily. The data synchronizer I mentioned would then be responsible for posting data changes back up to the client store for all connected clients, and you again get a reactive approach, but without the complete redraw cycle of React. The effect to the user would be the same.

Note that the current Goradd direction does not prevent a reactive approach. Its just that it would require a significant effort in building out the widgets, time I don't currently have, but I would welcome such contributions. The code generator, ORM, deployment, and underlying support libraries that are currently written would all support this. The code generator and ORM could be used to make API development easier as well. QCodo had a basic API generator. I am not experienced in good API development so someone would need to help here. Sorting out the issues of authorization, cookies, session management and the like through an API is not work I have planned. The other issue with React is that I have seen some really slow React websites. They are probably deployment issues, but it made me hesitant to invest the time. Someone with your experience could really help here.

As you said, QCubed/QCodo was really good at getting from the idea stage to a minimal viable product quickly. I am architecting things with an eye towards being able to start with SQL and basic HTML/Javascript widget generation, but then enable people to migrate a site to their own flavor of development required at scale, without needing a rewrite. One thought on this is I have restructured how the database adapters work so that potentially a NoSQL database could be dropped in to replace a SQL database and the ORM interface stays the same. There was a Node project, I think it was called SAILS, that inspired the idea. I think its generally doable. One-to-many relationships can be abstracted without too much trouble. Aggregation functions (SUM, MIN, etc.) are harder, but not everyone uses those.

There are lots of JQuery based widgets. JQueryUI is pretty much dead, but other similar projects are sprouting up to fill the void and to be more agnostic in terms of CSS frameworks supported (Bootstrap, etc.)

My current efforts are the following:
- Document everything using standard Go documentation techniques. This is about 60% done.
- Create detailed example uses of every built-in widget. This is just begun and is most of my effort for now.
- Achieve about a 60% code coverage on everything using travis-ci. Travis-ci is currently operational. Tests on the base support libraries and the ORM are done. I have created the ability to test forms by driving the browser, similar to Silenium, but without needing Silenium. Everything works through Goradd. So far, its working well. As I build the examples pages, I am also adding unit tests and browser based tests for each control. This is something we were not able to achieve in QCubed.
- Future effort will be to port the QCubed tutorial, to document and build tools to make starting a project quick and easy, and create a video demonstration.
- After that, take a breath and see what is next. Likely I would need to work an serialization/deserialization. The basic architecture is there for this. PHP had this built-in, so it was easy. I think a single Goradd instance could easily support thousands of users. Its really fast. To scale beyond this Goradd would need to serialize its form state to a data store. Doable, and the architecture is there, its just something for down the road.

Regarding mobile app development, I have personally been working on a Flutter project, and like what I see developing there. At some point, I will need to connect it to back end data, and so will be definitely exploring ways to do that. I see that Flutter supports WebSockets, and since Go has great Websocket support, that will likely be part of it.

Thoughts? Do you want to help?

**Comment by spekary** [comment]
An additional thought after re-reading your question. A while back I worked on splitting the ORM out from the panels in QCubed, and I am using the same approach here. So your request on splitting the code generation into two halves is already complete. 

The generated ORM is self-contained and can stand on its own and easily be used in an API. The forms engine likewise doesn't need the ORM. The generated UI puts the two together, but puts most of the combined code in the "connectors" which are sort of like View-Models. They are nice to use, but not required.

When you install Goradd, you get everything. But Go is compiled, so it doesn't really matter. Whatever you don't use is stripped out by the linker, and in the end you are deploying a highly optimized binary. Its very common in a Go project to have lots of open-source code in your source tree that never gets used. Since PHP is a scripted language, it was a concern because all that code would have to be selectively stripped out, or all of it deployed to the server. Its not a problem in Go.

**Comment by mintyPT** [comment]
> One goal of the project is accessibility. Since this is a framework, I would prefer not to limit it to only modern browsers. I just checked in some fixes so basic forms will work with javascript turned off. Later on, I hope to make it Opera Mini compatible. So the html generation in the default widgets is going to support progressive enhancement.

It's a valid point. Also, everyone know html/css and at least of bit of js but not everyone knows react/vue. This would certainly add some overhead and I remember liking QCubed because it was easy to get started even if you did not know everything.







> That said, neither do I want to limit to only HTML widgets. There are a ton of approaches to displaying javascript widgets. A few years ago I spoke with Mike Ho about this, and he thought the QCodo/QCubed approach could be adapted to AngularJS. I have thought about a React approach as well, and I have a private PHP version of a widget that does data synchronization for a MySQL database, sort of like CouchDB. Porting it to Goradd would not be hard and would provide the kind of data synchronization needed for a reactive approach, though pushing data down to the server is tricky in these situations.

Sadly, I never used CouchDB so don't really understand how that works, but no worries, not really important I guess.

> I think another approach could be supporting WebComponents/Polymer. This is a little easier, because the widget can be declared through the HTML, and the widget can be designed to send its data to the server through the current Ajax mechanism very easily. The data synchronizer I mentioned would then be responsible for posting data changes back up to the client store for all connected clients, and you again get a reactive approach, but without the complete redraw cycle of React. The effect to the user would be the same.

I'll leave you another alternative that I personally like. It's called [stimulus](https://github.com/stimulusjs/stimulus). It's from Basecamp, the creators of Ruby on Rails and the tagline is "A modest JavaScript framework for the HTML you already have". Take a look, you might like it. It could blend very well with your project.



> Note that the current Goradd direction does not prevent a reactive approach. Its just that it would require a significant effort in building out the widgets, time I don't currently have, but I would welcome such contributions. The code generator, ORM, deployment, and underlying support libraries that are currently written would all support this. The code generator and ORM could be used to make API development easier as well. QCodo had a basic API generator. I am not experienced in good API development so someone would need to help here. Sorting out the issues of authorization, cookies, session management and the like through an API is not work I have planned. The other issue with React is that I have seen some really slow React websites. They are probably deployment issues, but it made me hesitant to invest the time. Someone with your experience could really help here.

Well, I think we can forget about react (I agree about the slowness. If you do things in a certain way, you can easily have perf issues) for now but the API does interest me. On this I could try to contribute (more on that later), although I never really contributed to open source.


> As you said, QCubed/QCodo was really good at getting from the idea stage to a minimal viable product quickly. I am architecting things with an eye towards being able to start with SQL and basic HTML/Javascript widget generation, but then enable people to migrate a site to their own flavor of development required at scale, without needing a rewrite. One thought on this is I have restructured how the database adapters work so that potentially a NoSQL database could be dropped in to replace a SQL database and the ORM interface stays the same. There was a Node project, I think it was called SAILS, that inspired the idea. I think its generally doable. One-to-many relationships can be abstracted without too much trouble. Aggregation functions (SUM, MIN, etc.) are harder, but not everyone uses those.

Despite using mongo on my day job, I still ❤️ a good mysql database :)



> Regarding mobile app development, I have personally been working on a Flutter project, and like what I see developing there. At some point, I will need to connect it to back end data, and so will be definitely exploring ways to do that. I see that Flutter supports WebSockets, and since Go has great Websocket support, that will likely be part of it.

Will have to look into flutter. I've seen the name but never went investigate.

> Thoughts? Do you want to help?

Yes, but at the moment, I can't do any commitment to this for 2 reasons:

1. I'm trying to launch my own company on the side and it's taking all my free time;
2. Despite having some interest in go (due to it's speed, types, cross-plateform), I never wrote a single of it. I can start looking at it on the side to start. This might be my chance. What resources would you recommend to start learning it?

This is something I'd very much like to see evolve to the point (needs an api) were I could convince my company to use it.





> An additional thought after re-reading your question. A while back I worked on splitting the ORM out from the panels in QCubed, and I am using the same approach here. So your request on splitting the code generation into two halves is already complete.

That is awesome 👍 

> The generated ORM is self-contained and can stand on its own and easily be used in an API. The forms engine likewise doesn't need the ORM. The generated UI puts the two together, but puts most of the combined code in the "connectors" which are sort of like View-Models. They are nice to use, but not required.

This is also good news. 

> When you install Goradd, you get everything. But Go is compiled, so it doesn't really matter. Whatever you don't use is stripped out by the linker, and in the end you are deploying a highly optimized binary. Its very common in a Go project to have lots of open-source code in your source tree that never gets used. Since PHP is a scripted language, it was a concern because all that code would have to be selectively stripped out, or all of it deployed to the server. Its not a problem in Go.

My interest in go has been here for a long time now. Never had the time to start though.

One other language I know and like to use is python, and I heard most python devs are pleased with go so it's good news :)

**Comment by spekary** [comment]
To learn Go, start with https://tour.golang.org/welcome/1. Its a self-guided tour, very easy to use. You also get the Go Playground, where you can try out go code. Its not as good as using an IDE, but is really helpful for trying things out. When you get to the part about channels and go routines, if you are interested in async and concurrency, this can be really interesting to you. If it is confusing, then skip it because you don't really need it for most go programming. Its helpful for special situations though.

Go is a very easy to learn language. Other than channels and go routines, there is not much unique syntax. There are a couple of issues to get used to though.

1) You cannot have circular imports. This takes a while to get used to. It has a couple of benefits though, in that it forces better code organization, and that it allows the system to do incremental compiles quickly, usually in less than a second.
2) While it has some object oriented features, it is not at its core fully object oriented. In particular, virtual functions (the ability to stub a function to be implemented by a subclass) is not supported by the language. I have written a gist to show how to actually accomplish this using a programming pattern, so its possible to make it work. I use this for the Goradd control library, and it works fine. On the flip side, interfaces are fully supported.
3) No semicolons, and types come after the variable and not before. Seems like no big deal, but it can be hard when you are working on multiple projects in different languages.

Go is probably most often used for http APIs and other micro-service architectures. There are a ton of libraries supporting this, and the standard library has great http server support. Because of how interfaces work, its really easy to make middleware and plug in middleware if you use a particular pattern. See the MakeAppServer() function in web/app/app_base.go for an example of middleware chaining. Also, Amazon has announced that they support server-less programming using Go, and Google App Engine is in beta on this (funny that Amazon beat them to the release on this). 

Flutter I think is similar to ReactNative in its approach, or so I have heard. I have not used ReactNative. However, it has some significant advantages: 

- Supported by Google, 
- IDE is free and you can use the Android Development Kit as your Flutter IDE, 
- building Android and IOS apps from the same source is a piece of cake, 
- it uses the entire screen as a canvas, so creating engaging, interactive, branded interfaces is pretty easy.
- It uses the same kind of reactive approach in that you kind of draw everything in response to data changes. But its not ReactNative. It is compiled Dart code, and you get a fully native app that is not sitting on top of a runtime, so its much faster and more responsive than ReactNative.

Thanks for the lead on stimulus. I will check it out.

I hope your business launch goes well. I may be looking for work in a couple of months, so ping me at spekary-at-gmail.com if you need help.

**Comment by mintyPT** [comment]
It's been a while. 

I did the tour. I'm clearly not used to types and pointers and it's something I'd like to learn more (use more), specially types.

That being said, after doing the tour, I tried your project. Did the `go get github.com/goradd/goradd/..`and got blocked on :

> package goradd-project/config: unrecognized import path "goradd-project/config" (import path does not begin with hostname)
> package goradd-tmp/template: unrecognized import path "goradd-tmp/template" (import path does not begin with hostname)
> package goradd-project/gen/goradd/form: unrecognized import path "goradd-project/gen/goradd/form" (import path does not begin with hostname)
> package goradd-project/gen: unrecognized import path "goradd-project/gen" (import path does not begin with hostname)
> package goradd-project/web/app: unrecognized import path "goradd-project/web/app" (import path does not begin with hostname)
> package goradd-project/web/form: unrecognized import path "goradd-project/web/form" (import path does not begin with hostname)
> package goradd-project/gen/goradd/model: unrecognized import path "goradd-project/gen/goradd/model" (import path does not begin with hostname)
> package goradd-project/gen/goradd/model/node: unrecognized import path "goradd-project/gen/goradd/model/node" (import path does not begin with hostname)

This might be something easy but since I'm not used to the tools and ecosystem, I go stuck. Any ideas?

Also, regarding goradd, I don't have any clue were to look first to learn about it. I'm thinking I should code a couple of projects in go to get the feeling once I have time.

**Comment by spekary** [comment]
I am actively working on the examples right now and the quickstart. My goal is to finish the work to make it easy for someone like you to get started by the end of March. 

For now, did you get those messages while doing `go get github.com/goradd/goradd/..` or after that step when trying something else?

**Comment by spekary** [comment]
Also, what version of go are you using?

**Comment by mintyPT** [comment]
This is what happens 

![image](https://user-images.githubusercontent.com/1147911/54566554-7582a700-49d1-11e9-898e-c30f6d7a4524.png)

My version is `go version go1.12 darwin/amd64`

**Comment by spekary** [comment]
Giving you an update. I updated to Go 1.12 and discovered that Go 1.12 changed some things which has broken the travis build. I am working through those issues now, then I will get to working on the Quickstart process to get you up a running. Thanks for your patience.

**Comment by mintyPT** [comment]
Ah! Don't worry about it. I'm highly interested in this project and like I said I don't really have much time for this so I don't mind to wait a bit. 

As a side comment, when I worked with QCubed, it was only from the point of view of a developer building stuff with it without really understanding how it worked under the hood. This time, I want to take the time to understand how it works under the hood. 

Side question: After learning go, what did you build to get used to it?


> **Transformation doesn't take place with a vacuum; instead, it occurs when we are indirectly and directly connected to all those around us.**
> Byron Pulsifer

**Comment by spekary** [comment]
Following up on this. The quickstart process should now be working. See the Readme, and click on the Quickstart link, then follow the directions there. Let me know if you get it working.
